import { AppShell } from "@/components/app-shell";
import { getReport } from "@/app/actions/reports";
import { getUserTimeZone } from "@/app/actions/daily-tasks";
import { getDateKey } from "@/lib/domain/daily-generation";

export const dynamic = "force-dynamic";

export default async function ReportsPage({ searchParams }: { searchParams: Promise<{ from?: string; to?: string }> }) {
  const params = await searchParams; const today = getDateKey(new Date(), await getUserTimeZone()); const to = params.to ?? today; const from = params.from ?? to; const report = await getReport(from, to);
  const hours = (minutes: number) => `${Math.floor(minutes / 60)}h${String(minutes % 60).padStart(2, "0")}`;
  return <AppShell><div className="container py-10"><section className="mb-10"><p className="mb-3 text-sm font-semibold uppercase tracking-[.16em] text-[var(--accent)]">relatórios</p><h1 className="text-4xl md:text-6xl">Seu histórico, sem ruído</h1><p className="mt-3 max-w-xl muted">Compare planejamento e foco real por período.</p></section><form className="panel flex flex-wrap items-end gap-4 p-5"><label className="grid gap-1 text-sm font-semibold">De<input className="input" name="from" type="date" defaultValue={from} /></label><label className="grid gap-1 text-sm font-semibold">Até<input className="input" name="to" type="date" defaultValue={to} /></label><button className="btn btn-primary">Aplicar período</button></form><div className="mt-8 grid gap-4 md:grid-cols-4">{[["Tempo planejado", hours(report.plannedMinutes)], ["Tempo focado", hours(report.focusedMinutes)], ["Tarefas planejadas", report.plannedTasks], ["Concluídas", report.completedTasks]].map(([label, value]) => <div className="panel p-6" key={String(label)}><p className="text-sm muted">{label}</p><p className="number-display mt-3 text-3xl">{value}</p></div>)}</div><div className="panel mt-4 p-6 md:p-8"><h2 className="text-2xl">Planejado × realizado</h2>{Object.entries(report.byCategory).length ? <div className="mt-4 grid gap-3">{Object.entries(report.byCategory).map(([category, values]) => <div className="flex flex-wrap items-center justify-between gap-2 border-b border-[var(--line)] py-4" key={category}><span className="font-semibold">{category}</span><span className="number-display text-sm muted">{hours(values.plannedMinutes)} planejado · {hours(values.focusedMinutes)} focado</span></div>)}</div> : <p className="mt-2 muted">Ainda não há dados neste período.</p>}</div></div></AppShell>;
}
