"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";
import { createTemplate, updateTemplate } from "@/app/actions/templates";

const weekdays = ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"];
type TemplateFormValue = { id?: string; title: string; category: string; defaultStartTime: string; defaultDurationMinutes: number; daysOfWeek: number[] };

export function TemplateForm({ template, onCancel, onSaved }: { template?: TemplateFormValue; onCancel?: () => void; onSaved?: () => void }) {
  const router = useRouter(); const [error, setError] = useState(""); const [pending, setPending] = useState(false);
  async function submit(formData: FormData) { setPending(true); setError(""); const input = { title: String(formData.get("title")), category: String(formData.get("category")), defaultStartTime: String(formData.get("defaultStartTime")), defaultDurationMinutes: Number(formData.get("defaultDurationMinutes")), daysOfWeek: formData.getAll("daysOfWeek").map(Number) }; try { if (template?.id) await updateTemplate(template.id, input); else await createTemplate(input); router.refresh(); onSaved?.(); } catch (e) { setError(e instanceof Error ? e.message : "Não foi possível salvar a rotina."); } finally { setPending(false); } }
  return <form action={submit} className="panel grid gap-4 p-6"><div><h2 className="text-xl font-black">{template ? "Editar rotina" : "Nova rotina"}</h2><p className="mt-1 text-sm muted">{template ? "Atualize todos os campos da rotina." : "Cadastre uma vez e deixe o dia nascer organizado."}</p></div><label className="grid gap-1 text-sm font-bold">Nome<input className="input" name="title" placeholder="Faculdade" defaultValue={template?.title} required /></label><label className="grid gap-1 text-sm font-bold">Categoria<input className="input" name="category" placeholder="Estudo" defaultValue={template?.category} required /></label><div className="grid grid-cols-2 gap-3"><label className="grid gap-1 text-sm font-bold">Horário<input className="input" name="defaultStartTime" type="time" defaultValue={template?.defaultStartTime.slice(0, 5)} required /></label><label className="grid gap-1 text-sm font-bold">Duração (min)<input className="input" name="defaultDurationMinutes" type="number" min="1" step="1" defaultValue={template?.defaultDurationMinutes ?? 60} required /></label></div><fieldset><legend className="mb-2 text-sm font-bold">Dias da semana</legend><div className="flex flex-wrap gap-2">{weekdays.map((day, index) => <label key={day} className="flex items-center gap-1 text-sm"><input name="daysOfWeek" type="checkbox" value={index} defaultChecked={template?.daysOfWeek.includes(index)} />{day}</label>)}</div></fieldset>{error && <p className="text-sm text-red-700">{error}</p>}<div className="flex gap-2"><button className="btn btn-primary" disabled={pending}>{pending ? "Salvando..." : template ? "Salvar alterações" : "Criar rotina"}</button>{onCancel && <button type="button" className="btn btn-quiet" onClick={onCancel}>Cancelar</button>}</div></form>;
}
